export interface MockCompanyData {
  id: string;
  name: string;
  logo: string | null;
  description: string | null;
  website_url: string | null;
  linkedin_url: string | null;
  twitter_handle: string | null;
  github_url: string | null;
  industry: string | null;
  size: string | null;
  founded_year: number | null;
}

export interface MockJobData {
  id: string;
  ext_id: string;
  company: MockCompanyData;
  title: string;
  city: string | null;
  state: string | null;
  country: string | null;
  is_remote: boolean;
  work_model: 'remote' | 'hybrid' | 'onsite';
  contract_types: ('full-time' | 'part-time' | 'contractor' | 'internship' | 'temporary')[];
  published: string;
  expires_at: string | null;
  description: string;
  application_url: string;
  seniority: 'junior' | 'mid' | 'senior' | 'lead' | 'executive' | null;
  salary_min: number | null;
  salary_max: number | null;
  salary_currency: 'USD' | 'EUR' | 'GBP' | 'BRL' | 'CAD' | null;
  is_featured: boolean;
}

export const mockCompanies: MockCompanyData[] = [
  {
    id: '3797',
    name: 'Zscaler',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=zscaler',
    description: 'Cloud security company providing secure internet and web gateway services.',
    website_url: 'https://www.zscaler.com',
    linkedin_url: 'https://www.linkedin.com/company/zscaler',
    twitter_handle: 'zscaler',
    github_url: null,
    industry: 'Cybersecurity',
    size: '5000+',
    founded_year: 2007,
  },
  {
    id: '6348',
    name: 'Jane Street',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=janestreet',
    description: 'Quantitative trading firm and liquidity provider.',
    website_url: 'https://www.janestreet.com/',
    linkedin_url: 'https://www.linkedin.com/company/jane-street-global/',
    twitter_handle: 'JaneStreetGroup',
    github_url: 'https://github.com/janestreet',
    industry: 'Finance',
    size: '1000-5000',
    founded_year: 2000,
  },
  {
    id: '1001',
    name: 'TechFlow',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=techflow',
    description: 'Modern tech company building developer tools.',
    website_url: 'https://techflow.io',
    linkedin_url: 'https://www.linkedin.com/company/techflow',
    twitter_handle: 'techflow',
    github_url: null,
    industry: 'Technology',
    size: '100-500',
    founded_year: 2018,
  },
  {
    id: '1002',
    name: 'StartupHub',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=startuphub',
    description: 'Fast-growing startup building the future of work.',
    website_url: 'https://startuphub.com',
    linkedin_url: 'https://www.linkedin.com/company/startup-hub',
    twitter_handle: null,
    github_url: 'https://github.com/startup-hub',
    industry: 'Technology',
    size: '50-100',
    founded_year: 2020,
  },
  {
    id: '1003',
    name: 'DesignCo',
    logo: null,
    description: 'Design-focused company creating beautiful products.',
    website_url: 'https://designco.com',
    linkedin_url: 'https://www.linkedin.com/company/designco',
    twitter_handle: 'designco',
    github_url: null,
    industry: 'Design',
    size: '100-500',
    founded_year: 2015,
  },
];

export const mockJobs: MockJobData[] = [
  {
    id: '1488423',
    ext_id: '3979694634',
    company: mockCompanies[0],
    title: 'Cloud Operations Engineer (Networking, Linux, Python)',
    city: 'San Jose',
    state: 'CA',
    country: 'United States',
    is_remote: false,
    work_model: 'onsite',
    contract_types: ['full-time'],
    published: '2024-01-15T10:30:00Z',
    expires_at: '2025-03-15T10:30:00Z',
    description: '<p>Join our Cloud Operations team to maintain and scale our infrastructure. You will work with cutting-edge cloud technologies and help us deliver secure access to applications.</p><h3>Responsibilities</h3><ul><li>Monitor and maintain cloud infrastructure</li><li>Automate operational tasks using Python</li><li>Troubleshoot network issues</li></ul>',
    application_url: 'https://jobs.zscaler.com/cloud-ops-engineer',
    seniority: 'mid',
    salary_min: 94500,
    salary_max: 117000,
    salary_currency: 'USD',
    is_featured: true,
  },
  {
    id: '1200356',
    ext_id: '6524216002',
    company: mockCompanies[1],
    title: 'Python Infrastructure Engineer',
    city: 'New York',
    state: 'New York',
    country: 'United States',
    is_remote: false,
    work_model: 'onsite',
    contract_types: ['full-time'],
    published: '2024-01-14T14:20:00Z',
    expires_at: '2025-04-14T14:20:00Z',
    description: '<p>Build and maintain Python tooling at scale for one of the world\'s most sophisticated trading firms.</p>',
    application_url: 'https://boards.greenhouse.io/janestreet/jobs/6524216002',
    seniority: 'senior',
    salary_min: 150000,
    salary_max: 250000,
    salary_currency: 'USD',
    is_featured: true,
  },
  {
    id: '2231401',
    ext_id: 'REACT2024001',
    company: mockCompanies[2],
    title: 'Senior React Developer',
    city: null,
    state: null,
    country: null,
    is_remote: true,
    work_model: 'remote',
    contract_types: ['full-time'],
    published: '2024-01-13T09:15:00Z',
    expires_at: '2025-02-13T09:15:00Z',
    description: '<p>Looking for an experienced React developer to join our frontend team and build amazing user experiences.</p>',
    application_url: 'https://techflow.io/careers/react-developer',
    seniority: 'senior',
    salary_min: 120000,
    salary_max: 160000,
    salary_currency: 'USD',
    is_featured: true,
  },
  {
    id: '2231402',
    ext_id: 'FULLSTACK2024002',
    company: mockCompanies[3],
    title: 'Full Stack Developer (React + Node.js)',
    city: 'São Paulo',
    state: 'SP',
    country: 'Brazil',
    is_remote: true,
    work_model: 'hybrid',
    contract_types: ['full-time', 'part-time'],
    published: '2024-01-12T16:45:00Z',
    expires_at: '2025-02-12T16:45:00Z',
    description: '<p>Join a fast-growing startup building the future of work!</p>',
    application_url: 'https://startuphub.com/jobs/fullstack',
    seniority: 'mid',
    salary_min: 80000,
    salary_max: 110000,
    salary_currency: 'BRL',
    is_featured: false,
  },
  {
    id: '2231403',
    ext_id: 'FRONTEND2024003',
    company: mockCompanies[4],
    title: 'Frontend Engineer - UI/UX Focus',
    city: 'London',
    state: null,
    country: 'UK',
    is_remote: false,
    work_model: 'onsite',
    contract_types: ['full-time'],
    published: '2024-01-11T11:30:00Z',
    expires_at: '2025-02-11T11:30:00Z',
    description: '<p>Work closely with our design team to implement beautiful interfaces.</p>',
    application_url: 'https://designco.com/careers/frontend-engineer',
    seniority: 'mid',
    salary_min: 60000,
    salary_max: 85000,
    salary_currency: 'GBP',
    is_featured: false,
  },
  {
    id: '2231404',
    ext_id: 'NEXTJS2024004',
    company: {
      id: '1004',
      name: 'WebScale',
      logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=webscale',
      description: 'Scalable web solutions provider.',
      website_url: 'https://webscale.com',
      linkedin_url: null,
      twitter_handle: 'webscale',
      github_url: null,
      industry: 'Technology',
      size: '50-100',
      founded_year: 2019,
    },
    title: 'Next.js Developer - E-commerce Platform',
    city: null,
    state: null,
    country: null,
    is_remote: true,
    work_model: 'remote',
    contract_types: ['contractor'],
    published: '2024-01-10T08:00:00Z',
    expires_at: '2025-07-10T08:00:00Z',
    description: '<p>6-month contract to build a new e-commerce platform using Next.js 14.</p>',
    application_url: 'https://webscale.com/jobs/nextjs-contract',
    seniority: 'senior',
    salary_min: 90000,
    salary_max: 120000,
    salary_currency: 'USD',
    is_featured: false,
  },
  {
    id: '2231405',
    ext_id: 'JUNIOR2024005',
    company: {
      id: '1005',
      name: 'CodeAcademy Pro',
      logo: null,
      description: 'Educational platform for developers.',
      website_url: 'https://codeacademy-pro.com',
      linkedin_url: 'https://www.linkedin.com/company/codeacademy-pro',
      twitter_handle: null,
      github_url: null,
      industry: 'Education',
      size: '10-50',
      founded_year: 2021,
    },
    title: 'Junior React Developer',
    city: 'Berlin',
    state: null,
    country: 'Germany',
    is_remote: true,
    work_model: 'hybrid',
    contract_types: ['full-time'],
    published: '2024-01-09T13:20:00Z',
    expires_at: '2025-02-09T13:20:00Z',
    description: '<p>Perfect opportunity for someone starting their React journey!</p>',
    application_url: 'https://codeacademy-pro.com/careers/junior-react',
    seniority: 'junior',
    salary_min: 45000,
    salary_max: 60000,
    salary_currency: 'EUR',
    is_featured: false,
  },
  {
    id: '2231406',
    ext_id: 'LEAD2024006',
    company: {
      id: '1006',
      name: 'Enterprise Solutions Inc',
      logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=enterprise',
      description: 'Enterprise software solutions.',
      website_url: 'https://enterprise-solutions.com',
      linkedin_url: 'https://www.linkedin.com/company/enterprise-solutions',
      twitter_handle: 'enterprise_sol',
      github_url: null,
      industry: 'Enterprise Software',
      size: '1000-5000',
      founded_year: 2005,
    },
    title: 'Lead Frontend Architect',
    city: 'San Francisco',
    state: 'CA',
    country: 'United States',
    is_remote: true,
    work_model: 'hybrid',
    contract_types: ['full-time'],
    published: '2024-01-08T15:10:00Z',
    expires_at: '2025-03-08T15:10:00Z',
    description: '<p>Lead our frontend architecture decisions for a Fortune 500 company.</p>',
    application_url: 'https://enterprise-solutions.com/jobs/lead-architect',
    seniority: 'lead',
    salary_min: 180000,
    salary_max: 250000,
    salary_currency: 'USD',
    is_featured: true,
  },
  {
    id: '2231407',
    ext_id: 'MOBILE2024007',
    company: {
      id: '1007',
      name: 'MobileFirst',
      logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=mobilefirst',
      description: 'Mobile-first development company.',
      website_url: 'https://mobilefirst.com',
      linkedin_url: 'https://www.linkedin.com/company/mobilefirst',
      twitter_handle: 'mobilefirst',
      github_url: 'https://github.com/mobilefirst',
      industry: 'Mobile Development',
      size: '100-500',
      founded_year: 2016,
    },
    title: 'React Native Developer',
    city: 'Toronto',
    state: 'Ontario',
    country: 'Canada',
    is_remote: true,
    work_model: 'remote',
    contract_types: ['full-time'],
    published: '2024-01-07T10:05:00Z',
    expires_at: '2025-02-07T10:05:00Z',
    description: '<p>Build cross-platform mobile apps using React Native.</p>',
    application_url: 'https://mobilefirst.com/careers/react-native',
    seniority: 'mid',
    salary_min: 95000,
    salary_max: 130000,
    salary_currency: 'CAD',
    is_featured: false,
  },
  {
    id: '2231408',
    ext_id: 'STARTUP2024008',
    company: {
      id: '1008',
      name: 'GreenTech Innovations',
      logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=greentech',
      description: 'Fighting climate change through technology.',
      website_url: 'https://greentech.io',
      linkedin_url: 'https://www.linkedin.com/company/greentech-innovations',
      twitter_handle: null,
      github_url: null,
      industry: 'CleanTech',
      size: '10-50',
      founded_year: 2022,
    },
    title: 'Frontend Developer - Climate Tech',
    city: null,
    state: null,
    country: null,
    is_remote: true,
    work_model: 'remote',
    contract_types: ['full-time'],
    published: '2024-01-06T12:00:00Z',
    expires_at: '2025-02-06T12:00:00Z',
    description: '<p>Join our mission to fight climate change through technology!</p>',
    application_url: 'https://greentech.io/jobs/frontend',
    seniority: 'mid',
    salary_min: 85000,
    salary_max: 115000,
    salary_currency: 'USD',
    is_featured: false,
  },
  {
    id: '2231409',
    ext_id: 'BACKEND2024009',
    company: {
      id: '1009',
      name: 'DataDriven',
      logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=datadriven',
      description: 'AI-powered data analytics platform.',
      website_url: 'https://datadriven.ai',
      linkedin_url: 'https://www.linkedin.com/company/datadriven-ai',
      twitter_handle: 'datadriven_ai',
      github_url: null,
      industry: 'AI/ML',
      size: '100-500',
      founded_year: 2017,
    },
    title: 'Senior Backend Engineer (Go/Python)',
    city: 'Austin',
    state: 'TX',
    country: 'United States',
    is_remote: true,
    work_model: 'hybrid',
    contract_types: ['full-time'],
    published: '2024-01-05T09:00:00Z',
    expires_at: '2025-02-05T09:00:00Z',
    description: '<p>Build scalable backend systems for our AI platform.</p>',
    application_url: 'https://datadriven.ai/careers/backend',
    seniority: 'senior',
    salary_min: 140000,
    salary_max: 190000,
    salary_currency: 'USD',
    is_featured: false,
  },
  {
    id: '2231410',
    ext_id: 'DEVOPS2024010',
    company: {
      id: '1010',
      name: 'CloudNative Co',
      logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=cloudnative',
      description: 'Cloud-native infrastructure solutions.',
      website_url: 'https://cloudnative.co',
      linkedin_url: 'https://www.linkedin.com/company/cloudnative-co',
      twitter_handle: 'cloudnative_co',
      github_url: 'https://github.com/cloudnative-co',
      industry: 'Cloud Infrastructure',
      size: '50-100',
      founded_year: 2018,
    },
    title: 'DevOps Engineer - Kubernetes Specialist',
    city: null,
    state: null,
    country: null,
    is_remote: true,
    work_model: 'remote',
    contract_types: ['full-time'],
    published: '2024-01-04T14:30:00Z',
    expires_at: '2025-02-04T14:30:00Z',
    description: '<p>Manage and scale our Kubernetes infrastructure across multiple clouds.</p>',
    application_url: 'https://cloudnative.co/careers/devops',
    seniority: 'senior',
    salary_min: 130000,
    salary_max: 170000,
    salary_currency: 'USD',
    is_featured: false,
  },
];

let jobIdCounter = 2231411;

export function generateJobId(): string {
  return String(jobIdCounter++);
}

export function generateExternalId(): string {
  return `JOB${Date.now()}`;
}
